TEST_COMMAND=./test.sh

TEST_CLEAN = 



########################
# Include the base Makefile
PARENT_MAKE = Makefile.test
include ../../Makefile.inc

########################
# Add any additional targets here.
